name: Simple Package â€” Sequential macOS arm64 & Windows x64

on:
  workflow_dispatch: # you can also manually trigger this workflow
  push:
    branches:
      - main

jobs:
  build-macos-arm64:
    name: Build macOS arm64
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Show runner arch
        run: uname -m || true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Exercise 1: Implement dependency installation here
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          echo "TODO: Achieve pip requirements installation over here"

      # Remember to add a -n parameter to name the output binary appropriately for each platform
      - name: Build with PyInstaller (macOS arm64)
        run: |
          pyinstaller --onefile app/hello.py -n hello-macos-arm64
      - name: Debug dist
        run: ls -la dist || true
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-macos-arm64
          path: dist/hello-macos-arm64

  build-windows-x64:
    name: Build Windows x64
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Exercise 2: Implement Windows build steps here
      # You can refer to the macOS build steps above for guidance
      # - name: Build with PyInstaller (Windows x64)
      #   ...

      - name: Debug dist
        shell: pwsh
        run: dir dist || true

      # Exercise 3: Implement artifact upload here
      # - name: Upload Windows artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: hello-windows-x64
      #     path: # TODO: Specify the path to the Windows build artifact here.
      # it is a file with .exe extension named by you under `dist/`, generated in Exercise 2
